### ISSUE TITLE
[docs] Channels & Events section has incorrect example code

### ISSUE THREAD

**Issue by knownasilya** [netguru/ember-socket-guru#41]
<img width="795" alt="screen shot 2017-05-30 at 9 32 26 am" src="https://cloud.githubusercontent.com/assets/34726/26585732/05a1bf28-451b-11e7-9ef5-149bcdc9a43e.png">

It's identical to the "Events Only" section.

**Comment by jbandura** [comment]
good catch, thanks :) I'll fix this tomorrow 👍

**Comment by jbandura** [comment]
Fixed, thanks again for reporting :)
