### ISSUE TITLE
action-cable socket client cannot be instantiated

### ISSUE THREAD

**Issue by poteto** [netguru/ember-socket-guru#44]
# Expected behavior
Able to create an action-cable socket client

# Actual behavior
The action-cable socket client has only events in its observed channels structure. However, because the check in `_hasNoChannels` is [hardcoded](https://github.com/netguru/ember-socket-guru/blob/master/addon/services/socket-guru.js#L166) to only check against `socketio`, we are unable to instantiate an action-cable client.

**Comment by jbandura** [comment]
Released in 1.0.1 (https://github.com/netguru/ember-socket-guru/releases/tag/1.0.1), thanks again for your contribution!
