### ISSUE TITLE
Events-only Observed Channels Structure fails miserably

### ISSUE THREAD

**Issue by henrymazza** [netguru/ember-socket-guru#47]
structure-checker checks `observedChannels` for keys, but documentation states that `action-cable` and `socket.io` are events only, so "structure is a flat array". I think it's not being tested too.

I didn't go further to check if it's only a checker problem or somehow events-only structure got deprecated.

**Comment by henrymazza** [comment]
Sorry, the assertion that was failing did come from otherwhere. I was mistaken.

**Comment by henrymazza** [comment]
Ok. I'm having a bad time finding it, but nonetheless it could be better to use warnings instead of exploding my application because the checker can't find my `observedChannels` property. Couldn't it?

**Comment by henrymazza** [comment]
Eureka! The problem is that `socket-event-handler` mixin assumes you will use, and on my parlance _override_, the Ember Socket Guru™ service branded name instead of extending it, which should permit renaming. So I renamed and got the errors.

I'm sorry for so much noise! Now it works, consider adding an assertion to guarantee that the Service was properly named.

**Comment by jbandura** [comment]
that's a good point, will add an assertion. I'm sorry you experienced problems with this

**Comment by henrymazza** [comment]
One more thing... 

I know coffeescript is out of fashion, but it also breaks:
```
Error: EEXIST: file already exists, symlink '/Users/HMz/Development/uni/frontend/node_modules/ember-socket-guru/app/services/socket-guru.js' -> '/Users/HMz/Development/uni/frontend/tmp/broccoli_persistent_filtercoffee_script_filter-output_path-buvroTdq.tmp/frontend/services/socket-guru.js'
```

The guru service should be a mixin (interface pattern) or, better yet, once the service only contains config keys, it should be considered to use `app/app.js`.

Still I wouldn't want to include "isDevelopment?" in a high level service, I don't want my customer to know how I call my development machine, etc.; it's one thing that belongs to `ember-cli-build.js`, doesn't it? 

I appreciate how pretty the code and the examples look, and all the work done is very good -- If it weren't I would care, right? -- just need to be a little easier to debug and config. Cheers!
